### ISSUE TITLE
Implementing a more comprehensive .gitignore

### ISSUE THREAD

**Issue by matthewcmckenna** [cortinico/kotlin-android-template#12]
## ⚠️ Is your feature request related to a problem? Please describe

When getting started with the template and the first build new directories that are typically ignored for version control are not successfully ignored. (eg. various .xml files that relate to IDE config)

![image](https://user-images.githubusercontent.com/6266621/85205545-f70a6880-b2e9-11ea-85e6-c5c8724b0f4e.png)

## 💡 Describe the solution you'd like

A more comprehensive `.gitignore` could be used such as [this one](https://github.com/nisrulz/android-tips-tricks/blob/develop/android.gitignore) could be beneficial to this template as it is one less thing to worry about.

## 🤚 Do you want to develop this feature yourself?

- [x] Yes
- [ ] No

**Comment by cortinico** [comment]
Sure, this makes sense to update 👍

**Comment by matthewcmckenna** [comment]
Cool I'll open a PR!

**Comment by matthewcmckenna** [comment]
PR Here #13
