### ISSUE TITLE
Should use Compose BOM instead of reference to specific compose version

### ISSUE THREAD

**Issue by carstenhag** [cortinico/kotlin-android-template#186]
## ⚠️ Is your feature request related to a problem? Please describe
Nowdays it's recommended to use compose BOM versioning instead of hard references to using a specific version for all compose libraries. See https://developer.android.com/jetpack/compose/bom
## 💡 Describe the solution you'd like
A solution with version catalogs is explained at https://developer.android.com/jetpack/compose/bom#does_the_bom_work_with_version_catalogs. At work I am not using version catalogs yet so I can't get it working with a <2min PR 😢 

## 🤚 Do you want to develop this feature yourself?

- [ ] Yes
- [x] No (Note: At least not right now)

**Comment by cortinico** [comment]
This is a great point. I'm up for receiving a PR which introduces the compose BOM from you or anyone else who wants to do it 👍

**Comment by MJJacobs01** [comment]
Can I work on this one?
