### ISSUE TITLE
Add a flavor for Compose

### ISSUE THREAD

**Issue by chao2zhang** [cortinico/kotlin-android-template#26]
## ⚠️ Is your feature request related to a problem? Please describe
One of the use cases of this repo is to build sample projects for submitting bug reports. This has been a painpoint since my development directory is full of different sample projects, and often I need to upgrade to the latest version of the tools I used.

## 💡 Describe the solution you'd like
Add a flavor for using Jetpack Compose. As Compose still evolves rapidly, and I have been struggling a lot to keep a repo up-to-date with all the build setup.
The flavor could be a subproject or a different branch: I am open to any suggestion.

## 🤚 Do you want to develop this feature yourself?
- [ ] Yes
- [ ] No

**Comment by cortinico** [comment]
> The flavor could be a subproject or a different branch: I am open to any suggestion.

That's a great idea. I think we can have a `library-compose` module with a simple Compose-based UI.

**Comment by chao2zhang** [comment]
Compose actually requires the latest version of AGP, it also requires specific compiler flags. Adding compose as a library and using it in the same app module violates the purpose of having a working template.

I am debating with myself on whether creating a separate app module or using a different branch makes more sense.

**Comment by cortinico** [comment]
> I am debating with myself on whether creating a separate app module or using a different branch makes more sense.

I think that having a different branch is probably the easiest approach. When using a new template GH prompts you also if you want to "Include all branches" or not. We can merge the compose one into `master` once Compose hits a stable version of AGP.

**Comment by kenyee** [comment]
Probably worth merging that branch soon since Compose is at RC? (though initial release is also only a few weeks away :-)

**Comment by cortinico** [comment]
> Probably worth merging that branch soon since Compose is at RC? (though initial release is also only a few weeks away :-)

Well there is no such branch yet ¯\_(ツ)_/¯
Perhaps @GerardPaligot has one to share?

Anyway we can start working on one so we're ready for the release day 🎉

**Comment by kenyee** [comment]
Any suggestions for navigation to a compose module's UI?
Just occurred to me that if this is added, the demo app needs some sort of navigation...
