### ISSUE TITLE
Need example of flavor in build.gradle.kts

### ISSUE THREAD

**Issue by anticafe** [cortinico/kotlin-android-template#33]
## ⚠️ Is your feature request related to a problem? Please describe
In real project, we often have build flavor.

## 💡 Describe the solution you'd like
Add example of flavor `staging` and `production` in `build.gradle.kts`

## 🤚 Do you want to develop this feature yourself?

- [ ] Yes
- [x] No
(Sorry, I'm not so familiar with Kotlin Gradle script).

**Comment by cortinico** [comment]
That's a good idea. I've added a small snippet in #34
