### ISSUE TITLE
Replace ActivityTestRule with activityScenarioRule

### ISSUE THREAD

**Issue by liweijian** [cortinico/kotlin-android-template#42]
## ⚠️ Is your feature request related to a problem? Please describe
`ActivityTestRule` inside the espresso test case is deprecated .

## 💡 Describe the solution you'd like
I believe we could add [JUnit KTX extension library ](https://mvnrepository.com/artifact/androidx.test.ext/junit-ktx), and then:

```kotlin
@get:Rule val activityScenarioRule = activityScenarioRule<MainActivity>()
```

## 🤚 Do you want to develop this feature yourself?
- [x] Yes
- [ ] No

**Comment by cortinico** [comment]
Yup makes sense to me 👍 Please go ahead with `ActivityScenarioRule` and thank you for offering to do it 🙏
