### ISSUE TITLE
The Dependencies.kt mentioned in the README does not exist

### ISSUE THREAD

**Issue by binarynoise** [cortinico/kotlin-android-template#80]
The Dependencies.kt mentioned in the [README](../README.md) does not exist.

> Dependencies are centralized inside the [Dependencies.kt](buildSrc/src/main/java/Dependencies.kt) file in the `buildSrc` folder. This provides convenient auto-completion when writing your gradle files.

**Comment by cortinico** [comment]
You're right, we moved to Gradle Versions Catalog.

Do you want to send a PR to udpate the README? :) @binarynoise

**Comment by binarynoise** [comment]
@cortinico 
I'll create the PR.

Btw, does the libs.versions.toml really need to be in the gradle folder? Wouldn't it belong to the build-src as well?

**Comment by binarynoise** [comment]
OK. I created the PR.
