### ISSUE TITLE
Add short directory descriptions to the readme

### ISSUE THREAD

**Issue by Osiris-Team** [cortinico/kotlin-android-template#83]
## ⚠️ Is your feature request related to a problem? Please describe
No clue why there are so many directories and what they do.

## 💡 Describe the solution you'd like
Add directory descriptions to readme or docs.

## 🤚 Do you want to develop this feature yourself?

- [X] Yes
- [X] No

**Comment by cortinico** [comment]
Feel free to send a PR to add a section explaining them to the README (this is also up for grab if someone wants to contribute 👍 )

**Comment by Osiris-Team** [comment]
Very nice ;)
